package de.szut.lf8_project.domain.employee;

import de.szut.lf8_project.common.ValueType;

import java.util.Objects;

public class ProjectRole extends ValueType<String> {
    public ProjectRole(String qualification) {
        super(qualification);
    }


    // Generated by IntellJ
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ProjectRole that = (ProjectRole) o;
        return Objects.equals(this.unbox().toLowerCase().trim(), that.unbox().toLowerCase().trim());
    }

}